language: python

sudo: false

python:
  - 3.4.3
  - 3.5

services:
  - redis-server

install:
  - pip install -r requirements-dev.txt
  - python setup.py install

services:
  - redis-server

script:
  - flake8
  - rm -rf pulsar-queue
  - python -m runtests --coverage
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then python -m runtests --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
    - dev
